import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import TopLoadingBar from "@/components/Shared/TopLoadingBar";
import { CartProvider } from "@/context/CartContext";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <TopLoadingBar/> */}
      {/* <UserProvider> */}
      <ClerkProvider>
        <CartProvider>
          <Navbar/>
            {children}
          <Footer/>
        </CartProvider>
      {/* </UserProvider> */}
      </ClerkProvider>
      </body>
    </html>
  );
}
